apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: linkding
  name: linkding
  namespace: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  strategy: {}
  template:
    metadata:
      labels:
        app: linkding
    spec:
      containers:
        - image: ghcr.io/sissbruecker/linkding:latest
          name: linkding
          ports:
            - name: http
              containerPort: 9090
          env:
            # Required when serving over https://linkding.lab.dobreff.net
            - name: LD_CSRF_TRUSTED_ORIGINS
              value: "https://linkding.lab.dobreff.net"
          volumeMounts:
            - mountPath: /etc/linkding/data
              name: linkding-data
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data
